### ISSUE TITLE
Waduu 

### ISSUE THREAD

**Issue by Arya-was** [Rizxyu/RIXLE-BOT#69]
https://github.com/Rizxyu/RIXLE-BOT/blob/main/Lib/doujindesu.js
https://github.com/Arya-was/simple-api/blob/main/scraper/doujindesu.js

kok sama ya bang:v

**Comment by SanzGantengz** [comment]
Keren banh

**Comment by Arya-was** [comment]
Tutor scrape web?

**Comment by SanzGantengz** [comment]
Tutor canvas termuc?
