### ISSUE TITLE
multi prefix lom di up?

### ISSUE THREAD

**Issue by bulanbintang69** [Rizxyu/RIXLE-BOT#70]
yg digroup up dong..
pingin menikmati juga

**Comment by SanzGantengz** [comment]
Wow

**Comment by bulanbintang69** [comment]
> Wow

wow juga bang 😋 yah dinanti yang ter baeknya deh

**Comment by SanzGantengz** [comment]
> > Wow
> 
> wow juga bang 😋 yah dinanti yang ter baeknya deh

Ntar lah :v
Lagi pada mager update :v
mungkin :v

**Comment by bulanbintang69** [comment]
> > > Wow
> > 
> > 
> > wow juga bang 😋 yah dinanti yang ter baeknya deh
> 
> Ntar lah :v Lagi pada mager update :v mungkin :v

ok bang sesuai dengan nama github abangnya sanz aja.. tp ditunggu sih aslinya

**Comment by Rizxyu** [comment]
Nanti up kalo yg punya sc dah bikin versi final

**Comment by SanzGantengz** [comment]
> Nanti up kalo yg punya sc dah bikin versi final

Njirr :v

**Comment by Rizxyu** [comment]
> yg digroup up dong.. pingin menikmati juga

Udah di up bang

**Comment by Rizxyu** [comment]
> > > > Wow
> > > 
> > > 
> > > wow juga bang 😋 yah dinanti yang ter baeknya deh
> > 
> > 
> > Ntar lah :v Lagi pada mager update :v mungkin :v
> 
> ok bang sesuai dengan nama github abangnya sanz aja.. tp ditunggu sih aslinya

Sudah ada bang👍
