### ISSUE TITLE
Not important!

### ISSUE THREAD

**Issue by moo-d** [Rizxyu/RIXLE-BOT#88]
Change WhatsApp Group Link

<details>
  <summary>• ReadMe</summary><br>
  <details>
    <summary>• Code</summary>

```md
[![Group Bot](https://img.shields.io/badge/WhatsApp%20Group-25D366?style=for-the-badge&logo=whatsapp&logoColor=white)](https://chat.whatsapp.com/EBI5SZfyE8Z6i4UJpcs9Tl)
```

  </details>
  <details>
    <summary>• Result</summary>

[![Group Bot](https://img.shields.io/badge/WhatsApp%20Group-25D366?style=for-the-badge&logo=whatsapp&logoColor=white)](https://chat.whatsapp.com/EBI5SZfyE8Z6i4UJpcs9Tl)

  </details>
</details>

> Issue ini tidak penting, saya hanya bertanya link groupnya saja :/

**Comment by moo-d** [comment]
Semoga dibales sih :v

**Comment by moo-d** [comment]
Udah masuk :/

**Comment by Rizxyu** [comment]
Iyh

**Comment by Rizxyu** [comment]
https://chat.whatsapp.com/KGTBh3ocfzhJuveCHuCIXp
