### ISSUE TITLE
.

### ISSUE THREAD

**Issue by frmdeveloper** [Rizxyu/RIXLE-BOT#92]
"# Hi I'm Rizxyu

<p align="center">
  <a href="https://wa.me/6282328303332"><img src="https://github.com/Rizxyu/Rizxyu/raw/main/IMG-20211114-WA0123.jpg" alt="Velgrynd"></a>
</p>

<p align="center">
  <a href="https://wa.me/6282328303332"><img src="https://img.shields.io/badge/Contact Me-25D366?style=for-the-badge&logo=whatsapp&logoColor=white" />
</p>

<p align="center"> <a href="Rizxyu"><img width="170px" height="24" src="https://komarev.com/ghpvc/?username=Rizxyu&label=PROFILE%20VISITORS&color=green&style=flat-square" alt="Rizxyu" /></a> </p><br> 
<div align="center">

```js
Bukan Mastah😁 cuman newbie | Kalo mau nanya soal kode bisa chat saya
```

**My github Stats**
<p>&nbsp;<img align="center" src="https://github-readme-stats.vercel.app/api?username=Rizxyu&show_icons=true&theme=nightowl" alt="Rizxyu" /></p>
<p>&nbsp;<img align="center" src="https://github-readme-stats.vercel.app/api/top-langs/?username=Rizxyu&theme=algolia&layout=compact&langs_count=10&hide_border=true&show_icons=true" alt="Rizxyu"/></p></a><br> 

**Languages and Tools:**  
<code><img height="20" src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png"></code>
<code><img height="20" src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/kotlin/kotlin.png"></code>
<code><img height="20" src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/firebase/firebase.png"></code>
<code><img height="20" src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/nodejs/nodejs.png"></code>    

"
 https://raw.githubusercontent.com/Rizxyu/Rizxyu/main/README.md#:~:text=%23%20Hi%20I%27m%20Rizxyu,nodejs.png%22%3E%3C/code%3E

**Comment by Rizxyu** [comment]
Apa

**Comment by SanzGantengz** [comment]
Ggwp
